#!/usr/bin/env bash
#
# Compiles a Microvium .mvm.js source file into a C header containing the
# bytecode as a uint8_t array, so the firmware can #include it directly.
#
# Usage: gen_bytecode_header.sh <input.mvm.js> <output_header.h> <array_name>
#
set -euo pipefail

if [ "$#" -ne 3 ]; then
  echo "usage: $0 <input.mvm.js> <output_header.h> <array_name>" >&2
  exit 1
fi

INPUT="$1"
OUTPUT="$2"
ARRAY_NAME="$3"

if ! npx --no-install microvium --version > /dev/null 2>&1; then
  echo "error: the 'microvium' CLI is not installed locally." >&2
  echo "       Run 'npm install' in the project root first (see package.json)." >&2
  exit 1
fi

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

TMP_MVM="$TMPDIR/agent.mvm"
TMP_LOG="$TMPDIR/compile.log"

if ! npx --no-install microvium "$INPUT" --output-bytes -s "$TMP_MVM" > "$TMP_LOG" 2>&1; then
  cat "$TMP_LOG" >&2
  echo "error: microvium compile of $INPUT failed" >&2
  exit 1
fi

BYTES_LINE=$(grep '^{' "$TMP_LOG" || true)
if [ -z "$BYTES_LINE" ]; then
  cat "$TMP_LOG" >&2
  echo "error: could not find a bytecode array in microvium's output" >&2
  exit 1
fi

{
  echo "/* Auto-generated by tools/gen_bytecode_header.sh from $INPUT. Do not edit by hand. */"
  echo "#pragma once"
  echo "#include <stdint.h>"
  printf 'static const uint8_t %s[] = %s;\n' "$ARRAY_NAME" "$BYTES_LINE"
} > "$OUTPUT"

BYTECODE_SIZE=$(wc -c < "$TMP_MVM" | tr -d ' ')
echo "Generated $OUTPUT ($BYTECODE_SIZE bytes of Microvium bytecode)"
